Pubsub Subscribe/Unsubscribe ordering Bug Fix
skygear-demo/SkygearChat-iOS-Demo pull request #24
Opened 2017-10-27 12:13 UTC by howawong

Connects skygeario/chat#155

2017-10-30 08:16 UTC, carmenlau requested changes

2017-10-30 08:16 UTC, carmenlau commented on Swift Chat Demo 2/Info.plist
> +    </dict>
Please remove `NSAppTransportSecurity` setting. We should not add this to the PR.

2017-10-30 08:16 UTC, carmenlau commented on Swift Chat Demo 2/ConversationListViewController.swift
> +    override func viewWillDisappear(_ animated: Bool) {
Would you mind help adding `super` to functions like `viewWillDisappear`, `viewWillAppear`... etc? From the doc, we must call super for those functions.

https://developer.apple.com/documentation/uikit/uiviewcontroller/1621485-viewwilldisappear

2017-11-02 03:35 UTC, carmenlau commented
@howawong Could you help rebase? thanks!

2017-11-02 11:05 UTC, howawong commented
Continue at #25

2017-11-02 11:05 UTC, closed without merging